---
- hosts: vagrant_servers
  max_fail_percentage: 1
  serial: 1
  accelerate: false
  sudo: true


  roles:
    - Azulinho.azulinho-google-dns
    - Azulinho.azulinho-zabbix-server
    - Azulinho.azulinho-zabbix-agent
    - this-github-role

